routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\FrecuentClientPointsController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\SuppliersController;
use App\Http\Controllers\PurchasesController;
use App\Http\Controllers\MovementsController;
use App\Http\Controllers\BalancesController;
use App\Http\Controllers\NotificationsController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\NotificationsAdmiController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\ScheduleEmpController;
use App\Http\Controllers\EmpleadoController;





/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/auth/login');
});

/* Route::get('/client', function () {
    return view('client.index');
});

Route::get('/client/create', [ClientController::class,'create']);
*/
Route::resource('client', ClientController::class);

Route::resource('employee',EmployeeController::class);


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('role', RoleController::class);

Route::resource('frecuentClientPoints', FrecuentClientPointsController::class);
Route::get('/frecuentClientPoints/{frecuentClientPoint}/redeem', [App\Http\Controllers\FrecuentClientPointsController::class, 'redeem']);
Route::get('/frecuentClientPoints/{frecuentClientPoint}/list', [App\Http\Controllers\FrecuentClientPointsController::class, 'history_user']);

Route::get('/notificationsEmp', [App\Http\Controllers\NotificationsEmpController::class, 'index']);



Route::get('/evento2', [App\Http\Controllers\Evento2Controller::class, 'index']);
Route::get('/evento2/mostrar', [App\Http\Controllers\Evento2Controller::class, 'show']);
Route::post('/evento2/agregar', [App\Http\Controllers\Evento2Controller::class, 'store']);



Route::get('/evento3', [App\Http\Controllers\Evento3Controller::class, 'index']);
Route::get('/evento3/mostrar', [App\Http\Controllers\Evento3Controller::class, 'show']);
Route::post('/evento3/agregar', [App\Http\Controllers\Evento3Controller::class, 'store']);
Route::post('/evento3/editar/{id}', [App\Http\Controllers\Evento3Controller::class, 'edit']);
Route::post('/evento3/actualizar/{evento3}', [App\Http\Controllers\Evento3Controller::class, 'update']);
Route::post('/evento3/borrar/{id}', [App\Http\Controllers\Evento3Controller::class, 'destroy']);



/*Route::get('/employee',function () {return view('employee.index');});
Route::get('employee/create',[EmployeeController::class,'create']);*/

Route::resource('suppliers', App\Http\Controllers\SupplierController::class)->middleware('auth');
Route::resource('products', App\Http\Controllers\ProductController::class)->middleware('auth');
Route::resource('purchases', App\Http\Controllers\PurchaseController::class)->middleware('auth');
Route::resource('movements', App\Http\Controllers\MovementController::class)->middleware('auth');
Route::resource('balances', App\Http\Controllers\BalanceController::class)->middleware('auth');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

# agregamos vista de reportes
Route::get("list-blog", [App\Http\Controllers\DataController::class, "listBlogs"]);

Route::resource('gastos', App\Http\Controllers\GastoController::class)->middleware('auth');
Route::resource('dates', App\Http\Controllers\DateController::class)->middleware('auth');
Route::resource('requests', App\Http\Controllers\RequestController::class)->middleware('auth');

/*empleados y admi*/ 
Route::resource('notification',NotificationsController::class );
Route::resource('notificationsAdmi', NotificationsAdmiController::class);


Route::resource('schedule', ScheduleController::class);


Route::resource('scheduleEmp', ScheduleEmpController::class);




//empleado
/*Route::get('/empleado', function () {
    return view('empleado.index'); 
});

Route::get('/empleado/create', [EmpleadoController::class,'create']);
*/
Route::resource('empleado',EmpleadoController::class);

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Supplier
 *
 * @property $id
 * @property $Codigo
 * @property $Descripcion
 * @property $Telefono
 * @property $Provincia
 * @property $Canton
 * @property $Distrito
 * @property $Ubicacion
 * @property $Contacto
 * @property $created_at
 * @property $updated_at
 *
 * @property Purchase[] $purchases
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Supplier extends Model
{
    
    static $rules = [
		'Codigo' => 'required',
		'Descripcion' => 'required',
		'Telefono' => 'required',
		'Provincia' => 'required',
		'Canton' => 'required',
		'Distrito' => 'required',
		'Ubicacion' => 'required',
		'Contacto' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['Codigo','Descripcion','Telefono','Provincia','Canton','Distrito','Ubicacion','Contacto'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function purchases()
    {
        return $this->hasMany('App\Models\Purchase', 'supplier_id', 'id');
    }
    

}

app/Models/Suppliers.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Suppliers extends Model
{
    use HasFactory;
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Models\Supplier;
use Illuminate\Http\Request;

/**
 * Class SupplierController
 * @package App\Http\Controllers
 */
class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $suppliers = Supplier::paginate();

        return view('supplier.index', compact('suppliers'))
            ->with('i', (request()->input('page', 1) - 1) * $suppliers->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $supplier = new Supplier();
        return view('supplier.create', compact('supplier'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Supplier::$rules);

        $supplier = Supplier::create($request->all());

        return redirect()->route('suppliers.index')
            ->with('success', 'Supplier created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $supplier = Supplier::find($id);

        return view('supplier.show', compact('supplier'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $supplier = Supplier::find($id);

        return view('supplier.edit', compact('supplier'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Supplier $supplier
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Supplier $supplier)
    {
        request()->validate(Supplier::$rules);

        $supplier->update($request->all());

        return redirect()->route('suppliers.index')
            ->with('success', 'Supplier updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $supplier = Supplier::find($id)->delete();

        return redirect()->route('suppliers.index')
            ->with('success', 'Supplier deleted successfully');
    }
}

resources/views/supplier/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Supplier
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Crear Nuevo Proveedor</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('suppliers.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('supplier.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/supplier/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Editar Proveedor
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Editar Proveedor</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('suppliers.update', $supplier->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('supplier.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/supplier/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('Codigo') }}
            {{ Form::text('Codigo', $supplier->Codigo, ['class' => 'form-control' . ($errors->has('Codigo') ? ' is-invalid' : ''), 'placeholder' => 'Codigo']) }}
            {!! $errors->first('Codigo', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('Descripcion') }}
            {{ Form::text('Descripcion', $supplier->Descripcion, ['class' => 'form-control' . ($errors->has('Descripcion') ? ' is-invalid' : ''), 'placeholder' => 'Descripcion']) }}
            {!! $errors->first('Descripcion', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('Telefono') }}
            {{ Form::text('Telefono', $supplier->Telefono, ['class' => 'form-control' . ($errors->has('Telefono') ? ' is-invalid' : ''), 'placeholder' => 'Telefono']) }}
            {!! $errors->first('Telefono', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('Provincia') }}
            {{ Form::text('Provincia', $supplier->Provincia, ['class' => 'form-control' . ($errors->has('Provincia') ? ' is-invalid' : ''), 'placeholder' => 'Provincia']) }}
            {!! $errors->first('Provincia', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('Canton') }}
            {{ Form::text('Canton', $supplier->Canton, ['class' => 'form-control' . ($errors->has('Canton') ? ' is-invalid' : ''), 'placeholder' => 'Canton']) }}
            {!! $errors->first('Canton', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('Distrito') }}
            {{ Form::text('Distrito', $supplier->Distrito, ['class' => 'form-control' . ($errors->has('Distrito') ? ' is-invalid' : ''), 'placeholder' => 'Distrito']) }}
            {!! $errors->first('Distrito', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('Ubicacion') }}
            {{ Form::text('Ubicacion', $supplier->Ubicacion, ['class' => 'form-control' . ($errors->has('Ubicacion') ? ' is-invalid' : ''), 'placeholder' => 'Ubicacion']) }}
            {!! $errors->first('Ubicacion', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('Contacto') }}
            {{ Form::text('Contacto', $supplier->Contacto, ['class' => 'form-control' . ($errors->has('Contacto') ? ' is-invalid' : ''), 'placeholder' => 'Contacto']) }}
            {!! $errors->first('Contacto', '<div class="invalid-feedback">:message</p>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Enviar</button>
    </div>
    <div class="float-left">
        <a class="btn btn-success" href="{{ route('suppliers.index') }}"> Volver</a>
    </div>

</div>

resources/views/supplier/index.blade.php
@extends('layouts.app2')

<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Content-Language" content="en">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>Listar Proveedores - Ramenezco</title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
<meta name="description" content="Inline validation is very easy to implement using the Architect Framework.">
<meta name="msapplication-tap-highlight" content="no">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> 
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>--> 
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{{asset('css/app.css')}}">
<link rel="stylesheet" href="{{asset('css/custom.css')}}">
</head>
<body>
@if (Auth::guest())
<div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header"> @include('nav.top-nav-guest') </div>
<div class="app-main">
    <div class="app-main__outer">
        <div class="app-main__inner">
            <div class="app-page-title">
                <div class="page-title-wrapper">
                    <div class="page-title-heading">
                        <div class="page-title-icon"> <i class="pe-7s-drawer icon-gradient bg-happy-itmeo"> </i> </div>
                        <div>Listar Proveedores 
                            <!--<div class="page-title-subheading">Tables are the backbone of almost all web applications.
                                        </div>--> 
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="alert alert-danger" role="alert">
                    <h4 class="alert-heading">Buen Intento!</h4>
                    <p>Para acceder a nuestro sistema debes <a href="http://127.0.0.1:8000/">iniciar sesión</a>.</p>
                    <hr>
                    <p class="mb-0">Ramenezco App.</p>
                </div>
            </div>
            @include('nav.footer-nav') </div>
    </div>
</div>
</body>
</html>
@else
<div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">@include('nav.top-nav-index')</div>
<div class="app-main">@include('nav.side-bar-index')
    <div class="app-main__outer">
        <div class="app-main__inner">
            <div class="app-page-title">
                <div class="page-title-wrapper">
                    <div class="page-title-heading">
                        <div class="page-title-icon"><i class="pe-7s-drawer icon-gradient bg-happy-itmeo"></i></div>
                        <div>Listar Proveedores
                            <!--<div class="page-title-subheading">Tables are the backbone of almost all web applications.
                                        </div>-->
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="main-card mb-3 card">
                        <div class="card-body">
                            <h5 class="card-title">Proveedores</h5>
                            @if ($message = Session::get('success'))
                                <div class="alert alert-success">
                                    <p>{{ $message }}</p>
                                </div>
                            @endif
                            <div class="table-responsive">
                                <div class="float-left">
                                    <a href="{{ route('suppliers.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                      {{ __('Crear Nuevo Proveedor') }}
                                    </a>
                                  </div>  
                                <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>
                                        
										<th>Codigo</th>
										<th>Descripcion</th>
										<th>Telefono</th>
										<th>Provincia</th>
										<th>Canton</th>
										<th>Distrito</th>
										<th>Ubicacion</th>
										<th>Contacto</th>

                                        <th></th>
                                    </tr>

                                </thead>
                                <tbody>
                                    @foreach ($suppliers as $supplier)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            
											<td>{{ $supplier->Codigo }}</td>
											<td>{{ $supplier->Descripcion }}</td>
											<td>{{ $supplier->Telefono }}</td>
											<td>{{ $supplier->Provincia }}</td>
											<td>{{ $supplier->Canton }}</td>
											<td>{{ $supplier->Distrito }}</td>
											<td>{{ $supplier->Ubicacion }}</td>
											<td>{{ $supplier->Contacto }}</td>

                                            <td>
                                                <form action="{{ route('suppliers.destroy',$supplier->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('suppliers.show',$supplier->id) }}"><i class="fa fa-fw fa-eye"></i> Mostrar</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('suppliers.edit',$supplier->id) }}"><i class="fa fa-fw fa-edit"></i> Modificar</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Borrar</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                        </table>
   
                        </div>
                    </div> 
                    </div>
   
                </div>
            </div>
            
            
            @include('nav.footer-nav')</div>
    </div>
</div>


<script type="text/javascript" src="{{asset('js/main.js')}}"></script>
</body>
</html>
@endif

resources/views/supplier/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $supplier->name ?? 'Show Supplier' }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Mostrar Proveedores</span>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Codigo:</strong>
                            {{ $supplier->Codigo }}
                        </div>
                        <div class="form-group">
                            <strong>Descripcion:</strong>
                            {{ $supplier->Descripcion }}
                        </div>
                        <div class="form-group">
                            <strong>Telefono:</strong>
                            {{ $supplier->Telefono }}
                        </div>
                        <div class="form-group">
                            <strong>Provincia:</strong>
                            {{ $supplier->Provincia }}
                        </div>
                        <div class="form-group">
                            <strong>Canton:</strong>
                            {{ $supplier->Canton }}
                        </div>
                        <div class="form-group">
                            <strong>Distrito:</strong>
                            {{ $supplier->Distrito }}
                        </div>
                        <div class="form-group">
                            <strong>Ubicacion:</strong>
                            {{ $supplier->Ubicacion }}
                        </div>
                        <div class="form-group">
                            <strong>Contacto:</strong>
                            {{ $supplier->Contacto }}
                        </div>
                        <div class="float-left">
                            <a class="btn btn-primary" href="{{ route('suppliers.index') }}"> Volver</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection